# This is a basic workflow to help you get started with Actions

name: speed_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  speed_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install
        run: |
            sudo apt-get install curl
            curl -s https://install.speedtest.net/app/cli/install.deb.sh | sudo bash
            sudo apt-get install speedtest

      # Runs a set of commands using the runners shell
      - name: speedtest
        run: speedtest

